# Generated by Django 3.2.8 on 2021-10-31 15:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reading', models.CharField(choices=[('N', 'NATIVE'), ('E', 'EXCELLENT'), ('G', 'GOOD'), ('S', 'SATISFACTORY'), ('P', 'GOOPOORD')], default='G', max_length=1)),
                ('writing', models.CharField(choices=[('N', 'NATIVE'), ('E', 'EXCELLENT'), ('G', 'GOOD'), ('S', 'SATISFACTORY'), ('P', 'GOOPOORD')], default='G', max_length=1)),
                ('speaking', models.CharField(choices=[('N', 'NATIVE'), ('E', 'EXCELLENT'), ('G', 'GOOD'), ('S', 'SATISFACTORY'), ('P', 'GOOPOORD')], default='G', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_profile_img', models.ImageField(upload_to='images/')),
                ('first_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('full_address', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('date_of_birth', models.DateTimeField()),
                ('gender', models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE')], default='M', max_length=1)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('country_of_residence', django_countries.fields.CountryField(max_length=2)),
                ('phone_number', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+970'. Up to 9 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test1.language')),
            ],
        ),
    ]
