# Generated by Django 3.2.8 on 2021-10-31 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+970'. Up to 9 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
