# Generated by Django 3.2.8 on 2021-10-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_alter_client_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='linkedin_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
